/**
 * Publisher Agent
 * - Always exports Markdown to /runs/{runId}/paper.md
 * - PDF: print stylesheet only (no new lib added)
 * - Optional webhook: PUBLISH_WEBHOOK_URL env var (n8n-compatible POST)
 * - Fails gracefully if webhook unset or unreachable
 */

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import type {
  Draft,
  EvidenceTable,
  PublishResult,
  VerificationResult,
} from "../schemas";
import type { Emitter } from "../sse";

function verdictBadge(verdict: "supported" | "weak" | "unsupported"): string {
  switch (verdict) {
    case "supported": return "✅ VERIFIED";
    case "weak": return "⚠️ WEAK";
    case "unsupported": return "❌ UNVERIFIED";
  }
}

function buildMarkdown(
  topic: string,
  draft: Draft,
  table: EvidenceTable,
  verificationResults: VerificationResult[],
  runId: string
): string {
  const verdictMap = new Map(verificationResults.map((v) => [v.claimId, v]));

  const annotatedFindings = draft.findings.replace(
    /\[([^\]]+)\]/g,
    (match, id) => {
      const v = verdictMap.get(id);
      if (!v) return match;
      return `${match}[${verdictBadge(v.verdict)}]`;
    }
  );

  const refLines = table.papers
    .slice(0, 30)
    .map((p) => {
      const v = verificationResults.find((r) => r.claimId.startsWith(p.id));
      const badge = v ? ` — ${verdictBadge(v.verdict)}` : "";
      const authors = p.authors.slice(0, 3).join(", ");
      const more = p.authors.length > 3 ? " et al." : "";
      const doi = p.doi ? `\n  DOI: https://doi.org/${p.doi}` : "";
      const url = p.url && !p.doi ? `\n  URL: ${p.url}` : "";
      return `- **[${p.id}]** ${authors}${more} (${p.year ?? "n.d."}). *${p.title}*.${doi}${url}${badge}`;
    })
    .join("\n");

  return `# ${topic}

> Generated by PROVENANCE · Run ID: \`${runId}\` · ${new Date().toISOString()}

---

## Abstract

${draft.abstract}

---

## Findings

${annotatedFindings}

---

## Limitations

${draft.limitations}

---

## References

${refLines}

---

*This paper was autonomously generated by the PROVENANCE AI Research Team. All claims carry source citations. Verification status is shown per claim.*
`;
}

export async function runPublisher(
  runId: string,
  topic: string,
  draft: Draft,
  table: EvidenceTable,
  verificationResults: VerificationResult[],
  emit: Emitter
): Promise<PublishResult> {
  emit({
    agent: "publisher",
    status: "started",
    input_summary: `Publishing run ${runId}`,
  });

  // Write markdown
  const runDir = join(process.cwd(), "runs", runId);
  mkdirSync(runDir, { recursive: true });

  const md = buildMarkdown(topic, draft, table, verificationResults, runId);
  const mdPath = join(runDir, "paper.md");
  writeFileSync(mdPath, md, "utf-8");

  emit({
    agent: "publisher",
    status: "tool_call",
    tool_call: "write_markdown",
    result_summary: `Written to runs/${runId}/paper.md`,
  });

  // Optional webhook
  let webhookFired = false;
  let webhookStatus: number | undefined;
  const webhookUrl = process.env.PUBLISH_WEBHOOK_URL;

  if (webhookUrl) {
    emit({
      agent: "publisher",
      status: "tool_call",
      tool_call: "webhook",
      input_summary: "Firing publish webhook",
    });
    try {
      const res = await fetch(webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          runId,
          topic,
          timestamp: new Date().toISOString(),
          paperLength: md.length,
          claimCount: table.claims.length,
          verificationSummary: {
            supported: verificationResults.filter((r) => r.verdict === "supported").length,
            weak: verificationResults.filter((r) => r.verdict === "weak").length,
            unsupported: verificationResults.filter((r) => r.verdict === "unsupported").length,
          },
        }),
        signal: AbortSignal.timeout(10_000),
      });
      webhookFired = true;
      webhookStatus = res.status;
    } catch (err) {
      emit({
        agent: "publisher",
        status: "degraded",
        result_summary: `Webhook failed (non-fatal): ${String(err)}`,
      });
    }
  }

  emit({
    agent: "publisher",
    status: "done",
    result_summary: `Published. Markdown: ${mdPath}${webhookFired ? ` · Webhook: ${webhookStatus}` : ""}`,
  });

  return {
    runId,
    markdownPath: mdPath,
    webhookFired,
    webhookStatus,
  };
}
